server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

spring:
  application:
    name: Poc AI Integration

  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non_null

  kafka:
    producer:
      bootstrap-servers: host.docker.internal:9093  # Updated to SSL port
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        security.protocol: SSL
        ssl.truststore.location: C:\Works\isygo-it\01-wams-stack\00-service-stack-demo\05-kafka-integration\01-producer-consumer\certs/client.truststore.jks
        ssl.truststore.password: changeit
        ssl.keystore.location: C:\Works\isygo-it\01-wams-stack\00-service-stack-demo\05-kafka-integration\01-producer-consumer\certs/client.keystore.jks
        ssl.keystore.password: changeit
        ssl.key.password: changeit
        ssl.endpoint.identification.algorithm: ""
    consumer:
      bootstrap-servers: host.docker.internal:9093  # Updated to SSL port
      group-id: my-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        security.protocol: SSL
        ssl.truststore.location: C:\Works\isygo-it\01-wams-stack\00-service-stack-demo\05-kafka-integration\01-producer-consumer\certs/client.truststore.jks
        ssl.truststore.password: changeit
        ssl.keystore.location: C:\Works\isygo-it\01-wams-stack\00-service-stack-demo\05-kafka-integration\01-producer-consumer\certs/client.keystore.jks
        ssl.keystore.password: changeit
        ssl.key.password: changeit
        ssl.endpoint.identification.algorithm: ""
        enable.metrics.push: false
        session.timeout.ms: 60000
        heartbeat.interval.ms: 3000
        max.poll.interval.ms: 300000
    retry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus

kafka:
  topic:
    string-topic: string-topic
    file-topic: file-topic
    json-topic: json-topic
    xml-topic: xml-topic
  schemas:
    # Replace with absolute paths to actual schema files
    email-schema: file:/absolute/path/to/email-schema.json
    xml-message-xsd: file:/absolute/path/to/xml-message.xsd
  security:
    enable-hmac: false
    hmac-secret: ""
    enable-encryption: false
    aes-key: ""
    enable-json-validation: false
    enable-xml-validation: false

logging:
  level:
    root: INFO
    eu.isygoit.openai: DEBUG
    org.apache.kafka: DEBUG
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"