server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

spring:
  application:
    name: Poc AI Integration

  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non_null

  kafka:
    producer:
      bootstrap-servers: localhost:9093
      ssl:
        trust-store-location: classpath:/kafka-config/secrets/kafka.truststore.jks
        trust-store-password: truststore-password
        key-store-location: classpath:/kafka-config/secrets/kafka.keystore.jks
        key-store-password: keystore-password
        key-password: keystore-password
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
      properties:
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka-password";
        sasl.kerberos.service.name: kafka
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      bootstrap-servers: localhost:9093
      group-id: my-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      ssl:
        trust-store-location: classpath:/kafka-config/secrets/kafka.truststore.jks
        trust-store-password: truststore-password
        key-store-location: classpath:/kafka-config/secrets/kafka.keystore.jks
        key-store-password: keystore-password
        key-password: keystore-password
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
      properties:
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka-password";
        sasl.kerberos.service.name: kafka
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  retry:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus

kafka:
  topic:
    string-topic: string-topic
  schemas:
    email-schema: file:/path/to/email-schema.json
    xml-message-xsd: file:/path/to/xml-message.xsd
  security:
    enable-hmac: false
    hmac-secret: ""
    enable-encryption: false
    aes-key: ""
    enable-json-validation: false
    enable-xml-validation: false

logging:
  level:
    root: INFO
    eu.isygoit.openai: DEBUG
    org.apache.kafka: DEBUG
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"