server:
  port: 8081

spring:
  application:
    name: Multi tenacy - schema per tenant demo (H2)

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:tenants;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect

multi-tenancy:
  filter: TENANT # TENANT | CONTEXT
  mode: SCHEMA  # Still using SCHEMA strategy
  tenants:
    - id: tenants
      url: jdbc:h2:mem:tenants;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
      username: sa
      password: