server:
  port: 8081  # ? Set your custom server port

spring:
  application:
    name: Multi tenacy - schema per tenant demo

  h2:
    console:
      enabled: true
      path: /h2-console #http://localhost:8081/h2-console

  datasource:
    url: jdbc:postgresql://localhost:5432/tenants?currentSchema=public
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

multi-tenancy:
  filter: TENANT # TENANT | CONTEXT
  mode: SCHEMA  # DATABASE | SCHEMA | DISCRIMINATOR
  tenants:
    - id: tenants
      url: jdbc:postgresql://localhost:5432/tenants
      username: postgres
      password: root