# You must choose at startup between:
# SINGLE (default)
# DATABASE
# SCHEMA
# DISCRIMINATOR
spring:
  jpa:
    properties:
      hibernate:
        app:
  tenancy:
    enabled: true SCHEMA

app:
  tenants:
    tenant1:
      schema: tenant1_schema
    tenant2:
      schema: tenant2_schema