server:
  port: 8081

spring:
  profiles:
    active: h2
  application:
    name: Poc Multitenancy - discriminator tenant
  h2:
    console:
      enabled: true
      path: /h2-console #http://localhost:8081/h2-console

  datasource:
    url: jdbc:h2:mem:tenants;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

app:
  tenancy:
    enabled: true
    filter: TENANT # TENANT | CONTEXT
    mode: DISCRIMINATOR
    tenants:
      - id: tenants
        url: jdbc:h2:mem:tenants;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
        username: sa
        password:
