server:
  port: 8081

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  application:
    name: multitenancy - discriminator tenant demo

  h2:
    console:
      enabled: true
      path: /h2-console #http://localhost:8081/h2-console

  datasource:
    url: jdbc:h2:file:./data/tenants-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

multitenancy:
  filter: CONTEXT # TENANT | CONTEXT
  mode: GDM # DATABASE | SCHEMA | DISCRIMINATOR | GDM
  tenants:
    - id: tenants
      url: jdbc:h2:file:./data/tenants-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
      username: sa
      password:
