server:
  port: 8081  # ? Set your custom server port

spring:
  application:
    name: Multi tenacy poc
  h2:
    console:
      enabled: true
      path: /h2-ui

  datasource:
    url: jdbc:h2:file:./data/tenacy_discriminator_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    show-sql: true
    format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        multiTenancy: DISCRIMINATOR
        tenant_identifier_resolver: eu.isygoit.multitenancy.common.TenantIdentifierResolver
    hibernate:
      ddl-auto: update