server:
  port: 8081

spring:
  application:
    name: Poc Multitenancy - schema per tenant

  datasource:
    url: jdbc:postgresql://localhost:5432/tenants?currentSchema=public
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  tenancy:
    enabled: true
  filter: TENANT # TENANT | CONTEXT
  mode: SCHEMA  # DATABASE | SCHEMA | DISCRIMINATOR
  tenants:
    - id: tenants
      url: jdbc:postgresql://localhost:5432/tenants
      username: postgres
      password: root