# You must choose at startup between:
# SINGLE (default)
# DATABASE
# SCHEMA
# DISCRIMINATOR
spring:
  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA

app:
  tenants:
    TENANT1:
      schema: tenant1_schema
    TENANT2:
      schema: tenant2_schema