# You must choose at startup between:
# SINGLE (default)
# DATABASE
# SCHEMA
# DISCRIMINATOR
spring:
  jpa:
    properties:
      hibernate:
        multiTenancy: DATABASE

app:
  tenants:
    tenant1:
      url: jdbc:postgresql://localhost:5432/tenant1_db
      username: user1
      password: pass1
    tenant2:
      url: jdbc:postgresql://localhost:5432/tenant2_db
      username: user2
      password: pass2