server:
  port: 8081  # You can override this in tests if needed

spring:
  application:
    name: Multi-tenancy - H2 test profile


  h2:
    console:
      enabled: true
      path: /h2-console #http://localhost:8081/h2-console

  datasource:
    url: jdbc:h2:mem:masterdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

multi-tenancy:
  filter: TENANT # TENANT | CONTEXT
  mode: DATABASE  # DATABASE | SCHEMA | DISCRIMINATOR
  tenants:
    - id: tenant1
      url: jdbc:h2:mem:tenant1db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
      username: sa
      password:
    - id: tenant2
      url: jdbc:h2:mem:tenant2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
      username: sa
      password:
